name: example
description: Example application for dart_shelf_framework
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.3.0
  dart_shelf_framework:
    path: ../
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.0.0
