name: dart_shelf_framework
description: Everything you need to build a web server with Dart.
version: 0.1.1
repository: https://github.com/strivesolutions/dart-shelf-framework

environment:
  sdk: ^3.0.5

dependencies:
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
