name: Set CI Change Label when Workflow Changes

on:
  pull_request:

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Changed Workflow Files
        id: files
        run: |
          echo "{modified}={$(git diff --name-only --diff-filter=M ${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} -- .github/workflows/ | wc -l)}" >> $GITHUB_OUTPUT
          echo "{added}={$(git diff --name-only --diff-filter=A origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} -- .github/workflows/ | wc -l)}" >> $GITHUB_OUTPUT
      - name: label PR
        if: steps.files.outputs.modified != 0 || steps.files.outputs.added != 0
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          --header 'Authorization: Bearer ${{ github.token }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "labels": ["CI Change"]
          }'
